version: "3.9"
services:
  app:
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres15
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./src:/app/src     
    networks:
      - custom_network
    restart: always

  postgres15:
    container_name: postgres15
    build: ./database/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - custom_network
    restart: always

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:6.20
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: realanka77@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: kos
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   ports:
  #     - 5050:80
  #   networks:
  #     - custom_network
  #   restart: always
volumes:
  pgdata:
networks:
  custom_network:
      







